name: Go
on: [push]
jobs:
  old-go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: 1.15
      - uses: actions/checkout@v2
      - run: go build
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: 1.20.1
      - uses: actions/checkout@v2
      - run: go test
